<?
use Bitrix\Main\Localization\Loc;

$aMenuLinks = [
    [
        Loc::getMessage('MAIN_MENU_BRAIN_TITLE'), 
        'brain/', 
        [], 
        ['CODE'=>'brain'], 
        ''
    ],
    [
        Loc::getMessage('MAIN_MENU_THANKS_TITLE'), 
        'thanks/', 
        [], 
        ['CODE'=>'thanks'], 
        ''
    ],
    [
        Loc::getMessage('MAIN_MENU_QUESTION_TITLE'), 
        'question/', 
        [], 
        ['CODE'=>'question'], 
        ''
    ],
    [
        Loc::getMessage('MAIN_MENU_PARTICIPATE_TITLE'), 
        'participate/', 
        [], 
        ['CODE'=>'participate'], 
        ''
    ],
    [
        Loc::getMessage('MAIN_MENU_COMPETITION_TITLE'), 
        'competition/', 
        [], 
        ['CODE'=>'competition'], 
        ''
    ],
    [
        Loc::getMessage('MAIN_MENU_PHONEBOOK_TITLE'), 
        'phonebook/', 
        [], 
        ['CODE'=>'phonebook'], 
        ''
    ]
];
