<?
use Bitrix\Main\Localization\Loc;

$aMenuLinks = [
    [
        Loc::getMessage('MENU_COMPANY_TITLE'),
        'company/',
        [],
        [],
        ''
    ],
    [
        Loc::getMessage('MENU_MEDIA_TITLE'),
        'media/',
        [],
        [],
        ''
    ],
    [
        Loc::getMessage('MENU_PULSE_TITLE'),
        'pulse/',
        [],
        [],
        ''
    ],
    [
        Loc::getMessage('MENU_HR_TITLE'),
        'hr/',
        [],
        [],
        ''
    ],
    [
        Loc::getMessage('MENU_SERVICES_TITLE'),
        'services/',
        [],
        [],
        ''
    ],
    [
        Loc::getMessage('MENU_USEFUL_TITLE'),
        'useful/',
        [],
        [],
        ''
    ]
];